name: Compile Arduino
on:
  push:
    paths:
    - '**'  
jobs:
  build:
    name: Test compiling examples for MICRO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout custom library
        uses: actions/checkout@v2
        with:
          repository: sparkfun/SparkFun_MMA8452Q_Arduino_Library
          ref: master
          path: CustomLibrary # must contain string "Custom"
     
      - name: Checkout custom library wire
        uses: actions/eeprom@v2
        with:
          repository: arduino/ArduinoCore-avr 
          ref: master
          path: CustomLibrary_wire # must contain string "Custom"     
     
      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
          sketch-names: passw_0917.ino
          arduino-board-fqbn: arduino:avr:micro
